version: '3.8'

secrets:
  n8n_user:
    file: ./secrets/n8n_user.txt
  n8n_password:
    file: ./secrets/n8n_password.txt
  n8n_encryption_key:
    file: ./secrets/n8n_encryption_key.txt
  n8n_api_key:
    file: ./secrets/n8n_api_key.txt
  wilmer_api_key:
    file: ./secrets/wilmer_api_key.txt

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=saas_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/saas_db
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - WILMER_API_URL=http://wilmerai:8765
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  wilmerai:
    build:
      context: ./wilmerai
      dockerfile: Dockerfile
    volumes:
      - ./wilmerai/config:/app/Public/Configs
      - ./wilmerai/config/Users:/app/Public/Configs/Users
      - ./wilmerai/config/workflows:/app/Public/Configs/workflows
      - ./wilmerai/config/Routing:/app/Public/Configs/Routing
      - ./wilmerai/logs:/app/logs
      - wilmerai_data:/app/data
    ports:
      - "8765:8765"
    environment:
      # The following API keys are for third-party LLMs, not for WilmerAI itself
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - PYTHONUNBUFFERED=1
      - CONFIG_DIR=/app/Public/Configs
      - USER_CONFIG=default
    # Add the following to explicitly set the routing config path
      - ROUTING_CONFIG_PATH=/app/Public/Configs/Routing/default.json
    # Optional: If you want to secure the WilmerAI API with a key
    # Uncomment the following lines:
    # environment:
    #   - WILMER_API_KEY_FILE=/run/secrets/wilmer_api_key
    # secrets:
    #   - wilmer_api_key

    command: >
      sh -c "python -c 'import json; print(json.load(open(\"/app/Public/Configs/Routing/default.json\")))' && python /app/server.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_PRODUCTION=false
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_WEBHOOK_TUNNEL_URL=http://n8n:5678/
      # Using SQLite for initial setup without database dependency
      - DB_TYPE=sqlite
      - N8N_BASIC_AUTH_USER_FILE=/run/secrets/n8n_user
      - N8N_BASIC_AUTH_PASSWORD_FILE=/run/secrets/n8n_password
      - N8N_ENCRYPTION_KEY_FILE=/run/secrets/n8n_encryption_key
      - WEBHOOK_API_KEY_FILE=/run/secrets/n8n_api_key
      # Disable secure cookie for local development
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n:/tmp/workflows
      - ./secrets/n8n_user.txt:/run/secrets/n8n_user:ro
      - ./secrets/n8n_password.txt:/run/secrets/n8n_password:ro
      - ./secrets/n8n_encryption_key.txt:/run/secrets/n8n_encryption_key:ro
      - ./secrets/n8n_api_key.txt:/run/secrets/n8n_api_key:ro
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  n8n_data:
  wilmerai_data:


